spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.159.151.134:3306/secondeal?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: rencai
    password: RENcai123.
    view:
      prefix: /static/
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10Mb
      max-request-size: 10Mb

#spring.http.
freemarker:
    charset: UTF-8
    content-type: text/html
    cache: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    request-context-attribute: request
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mybatis-mapper/*/*.xml
  type-aliases-package: com.auction.model
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
